# Generated by Django 3.0.5 on 2021-03-08 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='code',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Codigo'),
        ),
        migrations.AddField(
            model_name='course',
            name='create_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
